apiVersion: 1

policies:
  - orgId: 1
    receiver: ops-email
    group_by: ["alertname", "grafana_folder"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: ops-email
        object_matchers:
          - ["severity", "=", "warning"]
        group_by: ["alertname", "grafana_folder"]
      - receiver: ops-email
        object_matchers:
          - ["severity", "=", "critical"]
        group_by: ["alertname", "grafana_folder"]
        repeat_interval: 1h
